apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-app
    app: demo-voting-app
spec:
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-app
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
  selector:
     matchLabels:
         name: voting-app
         app: demo-voting-app
  replicas: 1
